### ISSUE TITLE
Documentation note & thanks

### ISSUE THREAD

**Issue by stacksjb** [alanvardy/tod#157]
Thanks for this great resource! I've been looking for a reliable client to automate quick input of tasks into my inbox that supports todoist NLP, and my previous solutions were all over-complicated and didn't do that effectively. Installing this tool has allowed me to quickly add tasks easily - I've wrapped it with an Alfred workflow, and it works great (I'll link once I get it up on Github - thanks again!)

One quick comment - on Mac OS X, the configuration file is stored at ~/Library/Application Support/tod.cfg (took me some hunting to find) - would be great if you could add that to the documentation page!

Thanks again!

**Comment by stacksjb** [comment]
FWIW, the workflow wrapper (extremely simple) is here  https://github.com/stacksjb/AlfredTodWorkflow - thanks for this great solution that allowed me to quickly fix one of my major workflow pains!

**Comment by alanvardy** [comment]
Hi @stacksjb

Thank you very much for getting in touch!

I'll amend the documentation for the MacOS config file, and link to your workflow. Really happy to see more examples of this being used :slightly_smiling_face:  Leaving this open so I remember to do it!

**Comment by alanvardy** [comment]
Changes here, cheers.

https://github.com/alanvardy/tod/pull/161

**Comment by stacksjb** [comment]
Thanks! One other note that might be worth mentioning - the create a task in Inbox (by default) (-t) actually lets you create tasks with ANY labels or projects (because it uses the Doist NLP API) - so if you create a task using "-t Ship UPS Package #eBay @Errands p2 tomorrow" it would create a task in the eBay project, with the Errands label, with a priority of 2, due tomorrow.  (https://thesweetsetup.com/using-natural-language-with-todoist/ has some great guidelines on using NLP)
