### ISSUE TITLE
Invalid Token / API Error

### ISSUE THREAD

**Issue by stacksjb** [alanvardy/tod#223]
When I attempt to create a task in Tod, I get the following error:
`Error: Ok(
    "{\"error\":\"Invalid token\",\"error_code\":401,\"error_extra\":{\"access_type\":\"none\",\"event_id\":\"1288dd2c80a44b47b82079a0322c8c0a\",\"retry_after\":4},\"error_tag\":\"AUTH_INVALID_TOKEN\",\"http_code\":403}",
)`

I suspect this is a Todoist error, however I have:
-Tried with two different tokens from two different accounts as well as regenerated tokens - still received the same error
-Used those two tokens successfully to query the API manually - this has worked

-Has anyone else experienced this issue, or is it working correctly for you?
-Are you using the token from Settings -> Integrations -> Developer -> API Token or one generated from https://developer.todoist.com/appconsole.html?
-Would you be able to clarify/confirm the specific API endpoint Tod interacts with?

**Comment by tiagopassinato** [comment]
Same issue here... 401 Invalid Token. Seems like something changed on Todoist side?

**Comment by alanvardy** [comment]
I'm getting the same thing, it seems to have started very recently.

These are both from the `/sync/v9/` URL so I suspect that they probably just deprecated them. I'll work on getting a release out today.

**Comment by alanvardy** [comment]
> -Are you using the token from Settings -> Integrations -> Developer -> API Token or one generated from [developer.todoist.com/appconsole.html](https://developer.todoist.com/appconsole.html)?

I'm using `Settings -> Integrations -> Developer -> API Token` as well

**Comment by stacksjb** [comment]
Thanks for the quick response!  I agree - looks like something is broken, although /sync/v9 should be 

I would recommend, as a general rule, to use a token generated at https://developer.todoist.com/appconsole.html 
(Helps to improve with troubleshooting, allows throttling to happen per-token instead of per-user, and reduces the impact if the token is blocked or compromised)

To do so, go to the URL, and after logging in, click "Create a New App", give it a name, and then click "Create App". 
The Token can then be found under the "Test Token" section

For most regular users, an account token is fine, but if you're a heavy API user like me, I've ran into issues a few times from using the account token.

PS - for future API notifications, you can subscribe to the Todoist-API group (https://groups.google.com/a/doist.com/g/todoist-api/about)

**Comment by stacksjb** [comment]
Is this the issue? (Are you using token header instead of bearer?) 
https://groups.google.com/a/doist.com/g/todoist-api/c/sqrGTtCr-4A

**Comment by stacksjb** [comment]
I investigated the code, and the issue is that the Authorization:header is not present for the SYNC api (it is for the REST api)

The post_todoist_rest (Todoist_Rest API )has this:
`    let response = Client::new()
        .post(request_url)
        .header(CONTENT_TYPE, "application/json")
        .header(AUTHORIZATION, authorization)
        .header("X-Request-Id", new_uuid())
        .json(&body);
        println!("{:#?}", response);`

Whereas the post_todoist_sync (Todoist SYNC API) has this:
`let response = Client::new()
        .post(request_url)
        .json(&body)
        .send()
        .or(Err("Did not get response from server"))?;`
        
I don't know Rust, but modifying to this made it work successfully:

`   let response = Client::new()
        .post(request_url)
        .header(CONTENT_TYPE, "application/json")
        .header(AUTHORIZATION, "Bearer xxxxx")
        .json(&body);
        println!("{:#?}", response);
    let response = response
        .send()
        .or(Err("Did not get response from server"))?;
`

(Thx [cdstanford](https://github.com/cdstanford)  for the help troubleshooting)

**Comment by alanvardy** [comment]
> Thanks for the quick response! I agree - looks like something is broken, although /sync/v9 should be fine as it is the most recent API (v8 was deprecated a month ago)

This is good to know and huge relief, it has a lot of features that the rest API is just missing altogether.

> I would recommend, as a general rule, to use a token generated at [developer.todoist.com/appconsole.html](https://developer.todoist.com/appconsole.html)

Oh, I didn't know about this and had been using the other since the beginning.

> Is this the issue? (Are you using token header instead of bearer?) This was just deprecated today.

Bingo. Thanks for all the help troubleshooting @stacksjb. I'm modifying the code right now :+1:

**Comment by alanvardy** [comment]
Alright, thanks for making this so easy.

v0.3.1 is on `crates.io` and the `AUR` with fixes.
