### ISSUE TITLE
Change in task creation?

### ISSUE THREAD

**Issue by stacksjb** [alanvardy/tod#254]
I am getting reports that TOD task creation (tod -t) is broken on the latest version as of yesterday (https://github.com/stacksjb/AlfredTodWorkflow/issues/4) 

It appears to be an underlying issue with Tod

**Comment by stacksjb** [comment]
After testing, it appears that this is due to a change in how tasks are created. Before, task creation (of -t <task>) returned as success (✅), and as failure (❌). Now, it returns "Querying API" before returning the status code, which makes execution via script (as my workflow does) painful.


1) What change(s) were made to the task creation, if any - did the API method change? (There was a Todoist change to the legacy /items/add endpoint, but no changes to the quick add endpoint https://developer.todoist.com/sync/v9/#quick-add-an-item) 

2) Is there a way we can skip the querying status code (if needed, could it be done with a cli parameter?) Or only return responses when it is an error/failure? I'm relying on the success/failure to return notifications to the end user of the task being added successfully.

@alanvardy

**Comment by alanvardy** [comment]
I think that the only change is the querying API message that uses the `spinners` library. Tommorow I'll add a flag to disable the spinner and message and give you a ping to see if it fixes for you. Sorry for the breakage!

**Comment by stacksjb** [comment]
Perfect, thx!

**Comment by stacksjb** [comment]
FYI, this is no longer relevant, as I parse return status code now.
