### ISSUE TITLE
Mac notification says task creation has failed when it hasn't

### ISSUE THREAD

**Issue by dandineen** [alanvardy/tod#265]
Since updating my version of Tod to 0.3.3 every time I use Tod to make a new task via the Alfred UI I get a Todoist notification  informing me that task creation has failed.

![Screenshot 2023-03-29 at 09 04 29](https://user-images.githubusercontent.com/869732/228467712-420db521-26ac-4205-bb04-0b8739dbf540.png)

The notification also seems to show at least two attempts to query the API. A quick check of the Alfred debugger does indeed show a number of query attempts but no actual failures as far as I can see.

![Screenshot 2023-03-29 at 09 08 44](https://user-images.githubusercontent.com/869732/228468726-b63c7be6-96a4-4ee6-9be4-412ad93f1869.png)

The weird thing is a perfectly formed task turns up in Todoist a few seconds after the notification has disappeared. Everything seems to be working fine apart from the notification details.

Many thanks for all your hard work on Tod. It's awesome and I love using it :-)

**Comment by stacksjb** [comment]
Hi @dandineen -

For issues with the Alfred Wrapper, please open them under https://github.com/stacksjb/AlfredTodWorkflow 

To rule out TOD, simply try creating the task directly with the "tod -t" works. 

Because you are getting the "Querying API" response, that means that spinners haven't been disabled - most likely hat is your issue. Change the value for "Spinners" from 'null' to 'false' in the tod.cfg file

**Comment by dandineen** [comment]
Thank you for getting back to me @stacksjb and apologies for dropping this issue in the wrong place.

Task creation with `tod -t` works without issue so I guess it's something to do with the Alfred wrapper. I'll open an issue there instead and hopefully get it sorted without too much back and forth. 

Not being a dev I'm afraid I wasn't sure where I would find the tod.cfg file or how I would go about editing it. I wasn't certain whether the 'spinners' are something to do with TOD or the Alfred integration. Sorry for being dense!

**Comment by stacksjb** [comment]
On Mac, the tod.cfg file is found in the application support folder for your user, at "~/Library/Application\ Support/tod.cfg"

You can edit it manually like so:
-In Finder, click on the "Go" then "Go To Folder..." menu item
![image](https://user-images.githubusercontent.com/2865491/228879241-d1f05961-8361-4027-b26e-8cd0bd5edb79.png)
-Then in the box that appears, paste "~/Library/Application Support/tod.cfg"
![image](https://user-images.githubusercontent.com/2865491/228880080-8b6f3266-5e84-40c2-b340-841789eb725d.png)
-Open the tod.cfg file (if you don't have a preferred text editor, you can use TextEdit)
-Change the line for "spinners" from "null" to "false"
![image](https://user-images.githubusercontent.com/2865491/228881711-8e357932-3c72-4288-bf1e-41698e184d95.png)
-Save and exit

**Comment by stacksjb** [comment]
HI @dandineen,

The latest version should work regardless of your spinners config. Give it a shot.

Thanks!

**Comment by alanvardy** [comment]
Haha, both of you are much appreciated. It's a great feeling to show up to a thread late and find out everything got solved without me :laughing:

**Comment by dandineen** [comment]
@stacksjb I've updated TOD to 0.3.4 and updated the Alfred workflow to the latest version and ... everything is working perfectly! Thanks again for taking the time to respond to me - I really appreciate your patience.

Oh, and when was that task creation trumpet fanfare introduced? It gave me big LOLs :-)
