### ISSUE TITLE
Simple alias example for anyone interested

### ISSUE THREAD

**Issue by richard-edwards** [alanvardy/tod#266]
In case anyone wants this, I created a small alias for 't' in my oh-my-zsh alias file so you can do:

t <project> <task> without the option flags. Just easier to remember for me :)

```
function t() {
  if [ -z "$1" ]; then
    echo "Usage: t <project> <task>"
    tod -l
    return
  fi
  project=$1
  shift
  echo "Adding '$@' to $project"
  tod -p "$project" -t "$@"
}
```

**Comment by alanvardy** [comment]
Something similar for fish, i use this for the home project specifically and have a few others for work etc

```bash
function th
  t -p home -t  $argv; 
end
```
