### ISSUE TITLE
Exit Codes?

### ISSUE THREAD

**Issue by stacksjb** [alanvardy/tod#268]
While working on modifying the logic for the Alfred Wrapper, I realized that it would be much cleaner to  
simply call TOD to run in the background, and then return the status based on the exit code (instead of parsing the CLI output, as I am currently doing)

@alanvardy can you confirm if there are any other exit codes I should be aware of? 
It appears that 0 is return for successful (expected) and 2 is returned for missing parameters; are there any others?

I have tested a modified version that monitors for the 0 exit code on task creation and acts on that and it works really well, without any need to handle spinners or config modification.

**Comment by alanvardy** [comment]
Hi @stacksjb I also return an error code 1 for errors that are handled manually, all successful things will indeed return a 0 :+1:

**Comment by alanvardy** [comment]
Link to code where I return exit code 1: https://github.com/alanvardy/tod/blob/4384072939b7f503078c64aefdc4d0cfee2bd971/src/main.rs#L143

**Comment by stacksjb** [comment]
Perfect, thx. I'll add handling logic! 

I've updated wrapper and it appears to work really well. Thanks!
