### ISSUE TITLE
Way to import projects?

### ISSUE THREAD

**Issue by stacksjb** [alanvardy/tod#303]
I love the ability to sort projects and especially process through inbox, but it is counterintuitive/difficult to have to go through each project and add to local config (with ID, etc), especially when my Todoist projects change.

Is there any way to pull projects and import into config? Does that functionality exist? It would be great if that was automated so that the Inbox was the Todoist inbox.

**Comment by alanvardy** [comment]
I like this idea, I will add a `tod project import` to the API after the current work is in

**Comment by alanvardy** [comment]
Putting a little more thought into this, my initial thought around the flow would be:
1. user is prompted to confirm that they want to delete all projects from config if there are any in there
2. All projects deleted in config
3. Fetch all projects from API
4. Loop through the projects and prompt user to accept current name or rename to a different alias, then save each project to config.

Does that make sense and seem optimal for your usecase? The alternative is that I could check the project ids in config and only import those that are not already in config.

**Comment by stacksjb** [comment]
This definitely meets use case. The simplest use case is being able to quickly import some or all projects.

A more complex situation would be if there are new updates to be added or modified, but that could be handled simply with the same workflow (or by keeping existing config and rerunning the workflow.) The more ideal method would be tp allow for prompting on any projects that aren't already local to see if they need to be added, but that might be more work than worth.

**Comment by alanvardy** [comment]
Notes for self:

- [ ] Get all projects
- [ ] For projects that already exist prompt to rename them
- [ ] For projects that don't exist, prompt to either set a name or skip

**Comment by alanvardy** [comment]
PR up for this, can add or skip. Renaming to be done in another PR.

**Comment by alanvardy** [comment]
PR: https://github.com/alanvardy/tod/pull/356
