### ISSUE TITLE
Complete next doesn't take into account that next can be None

### ISSUE THREAD

**Issue by titoOdUA** [alanvardy/tod#327]
It's a little suggestion to add error handling to the complete next functionality.

Right now it doesn't take into account that there can be situations when the next issue is not set or has been already completed.
As a result, it always returns success, which is a little missleading

You can think that you have completed something when you have not.
You can freak out that it is completing some random tasks (like I have =) )

I propose to return a text that will explicitly tell that there is no next task right now.
Have some wip commit to address it.

**Comment by alanvardy** [comment]
Thanks for the issue, this is a valuable fix :+1:

**Comment by alanvardy** [comment]
Merged,
