### ISSUE TITLE
Feature: ability to skip task in 'project process' command

### ISSUE THREAD

**Issue by titoOdUA** [alanvardy/tod#329]
Problem: when processing the project's tasks there is no ability to skip the task, only to complete it or stop processing the project's tasks.

I find it inconvenient. It is a fairly realistic scenario when you may need to complete a task that isn't in order of the sorting method used in tod.

I would like to be able to process all the tasks if I want to, regardless of the order of tasks or value sort.
I think it is fairly reasonable, because of the fact that everyone would have slightly different workflows.

I hope it isn't against the philosophy of the repo.

**Comment by alanvardy** [comment]
Haha, skipping tasks could become a bad habit but monitoring that is probably the responsibility of the user.
