### ISSUE TITLE
Add due flag to tod task create

### ISSUE THREAD

**Issue by alanvardy** [alanvardy/tod#338]
Here are the docs for create task on the Todoist API https://developer.todoist.com/rest/v2/#create-a-new-task

Add a due-date flag to the `tod task create` command. There is no default. Validate that it is in the format `YYYY-MM-DD`

```bash
tod task create --due-date "2024-02-30"
```

**Comment by alanvardy** [comment]
Alternately we can also use the inquire library's date picker! I'm not sure which is better at this point.

**Comment by stacksjb** [comment]
I would recommend merging due_date and due_string to just "due", and then
If entered in format of YYYY-MM-DD set as due-date
Otehrwise set as due_string

it's worth noting that todoist also supports due at specific time (vs just date), so YYYY-MM-DD HH:MM is also valid (it will use your account timezone in this case, unless you override it with a specific timezone in the API call)

**Comment by alanvardy** [comment]
Agreed :+1:
