### ISSUE TITLE
tod task list -s not working

### ISSUE THREAD

**Issue by alanvardy** [alanvardy/tod#341]
Showed no tasks even when I had one due today.

**Comment by alanvardy** [comment]
Turns out it was working properly but I had forgotten that it only shows tasks with a time on them. I opened a PR that clarfies what it does a little better.

**Comment by stacksjb** [comment]
Oh no, is this code getting so complex we're startng to forget what it does? 😆

**Comment by alanvardy** [comment]
> Oh no, is this code getting so complex we're startng to forget what it does? laughing

Haha, with my memory, it just had to exceed a handful of lines to get there :smile:
