### ISSUE TITLE
Bulk import tasks

### ISSUE THREAD

**Issue by alanvardy** [alanvardy/tod#365]
This could be a

`tod task import /path/to/file.md`

And then the file could be in format

```markdown
- This is a main task p1
 - This is a subtask p2
- This is another task
```

And then the user is prompted for which project they should be inserted into

Maybe we could get a little crazy and also find or create the project as well?

```markdown
# ProjectOne

- This is a main task p1
 - This is a subtask p2
- This is another task

# ProjectTwo

- This task is in another project
```

**Comment by alanvardy** [comment]
I think that Todoist has an excellent "complex" import option, and maybe we can just support the simple case.

Would you consider using this? How about you @titoOdUA ? I do have situations where I have a list of tasks in my text editor and would love to just select them and use a command to pipe them straight into Todoist... but I wouldn't say that this is a critical feature for me.

**Comment by stacksjb** [comment]
I like this suggestion. I currently copy/paste delimited lists (1 per newline) into Todoist as tasks. I would use an import feature.

**Comment by BobToninho** [comment]
I would start by adding a simple-as-possible plaintext bulk import. No markdown, no lists. Just a line by line import, every line is a task. This would give us a foundation on the import logic, with the possibility to extend it in the future

**Comment by stacksjb** [comment]
Let's do that, then spawn another request for subtasks.

From what I can tell, we don't really specifically support subtasks at the moment anyway (just treat them as another/regular task) so that's a future item.

**Comment by BobToninho** [comment]
I will start working on this (if Alan agrees on my solution) then!

**Comment by alanvardy** [comment]
I like it! I really appreciate you guys putting so much thought into it :+1:

**Comment by alanvardy** [comment]
Implemented and released, check out `list import`

**Comment by stacksjb** [comment]
I am not sure if this was documented - tagging for documentation
