### ISSUE TITLE
Add "Skip" option to tod project empty

### ISSUE THREAD

**Issue by stacksjb** [alanvardy/tod#376]
Using "Tod Project Empty" to process out my Inbox and project folders is SO useful. Tell me where I can send you the $500 for saving me a bunch of time with this workflow :)

However, when processing out other projects (Besides Inbox), I don't necessarily want to act on all the tasks.

Please add a "skip" option under "complete" which will skip the item with no action and move onto the next task in the project.

**Comment by stacksjb** [comment]
This should also be added to "schedule", "Prioritize", and "process"

(I recognize this sort of goes against ideal GTD workflow, but it's appropriate for task processing)

**Comment by alanvardy** [comment]
Haha, yeah I use this daily too and am also slightly uncomfortable with the `skip` option but people do need it.

**Comment by stacksjb** [comment]
Example areas:

Schedule:
Current:
`? Input a date in natural language or (c)omplete`
Change to
`? Input a date in natural language, (s)kip, or (c)omplete`

Prioritze:
Current:
`? Choose a priority that should be assigned to task:
> LOW
  MEDIUM
  HIGH`

Chagnge to::
? Choose a priority that should be assigned to task:
```
> LOW
  MEDIUM
  HIGH
 SKIP
```

Tod project empty
Current:
```
 % tod project empty
> Select project TEST
No Priority
? Enter destination project name or complete:
> complete
  🩺 Health
v 🏠 House
```

Change to:
```
% tod project empty
> Select project TEST
No Priority
? Enter destination project name or complete:
> complete
  🩺 Health
v 🏠 House
Skip
```

Skip is already present on 'project process'
All of above can mirror on later filter additions.

**Comment by alanvardy** [comment]
I'm enjoying the issues you are opening and the project management role you've taken on; it's accelerated progress on this app. Just trying things out and thinking about the UX is a huge boon for me, and I can then focus on cranking out a PR here and there.

When you are ready to dig into Rust, make sure to let us know! I have some recommendations and can't wait for your first PR.
