### ISSUE TITLE
Add "Tod project label"

### ISSUE THREAD

**Issue by stacksjb** [alanvardy/tod#377]
Similar to the "Tod Project Empty", which moves tasks into other projects, I action items by adding labels to the tasks.

I would love a similar workflow such as "tod project label" which would go through each item in the box and let me select label(s) to add to the task.

The workflow would be very similar to the "tod project empty" - display the labels to add in the list, select them, and then add them to the list, with the following key features/items:

1) You would need to be able to select multiple labels, sequentially from the list (so selecting an item would return to the the top with the same item, adding the label selected to the label list
2) Then the "complete" would instead be "Done" which would move on to the next item

**Comment by stacksjb** [comment]
This could either accept a text input or could allow you to select from list.

Once a label is selected from the list, it would need to be removed from the display list (and added to the list of labels).

Example workflow could look very similar to "Tod project empty"
![image](https://github.com/alanvardy/tod/assets/2865491/d479481e-f959-4e91-b5aa-fb1ed4df5148)

Two other use case/points to note:
1) Do we want to allow ability to select/remove existing labels, or make a separate workflow (maybe a 'relabel'?). For me, I primarily would want to add labels, not remove, but I could see a use case for combining. I think it might be easiest if we just relabel as listed (including removing and adding).

Another option could be to display the labels at the top of the list with some sort of checkbox and/or list them already, and then just include whatever is present

2) For my workflow, I have a filter for unlabeled and review from those. We could add a tag for --empty (to filter only for items without a label), or probably just apply this same logic to the "tod filter" workflow so I can label from there.

**Comment by alanvardy** [comment]
Adding labels is now covered by `tod filter label` ! You can use a filter to select the tasks you wish to label, and the labels you wish to select from.
