### ISSUE TITLE
Prioritize/sort selections

### ISSUE THREAD

**Issue by stacksjb** [alanvardy/tod#378]
When selecting destination projects, tasks, labels, etc, what sort are the items displayed in? 

It doesn't appear alphabetical nor does it appear the same as they are sorted within the official Todoist App. It initially appeared ot match the tod.cfg, however editing that doesn't seem to match either.

It would be ideal if they were sorted, either alphabetically or(ideally) returned in their custom-sorted order (the official API includes an "order" value). The second option seems best to me because then you can simply instruct users to re-order them in the app in the order they would like them returned.

In addition (this could be a feature that could be enabled/disabled) it would be nice if recent selections could be prioritized or 'pinned' to the top.

**Comment by stacksjb** [comment]
Successful use case:

1) Items (Projects, labels, filters, etc) are returned in order of their "Sort Order" as defined in Todoist/returned by API

**Comment by stacksjb** [comment]
Task sorting is under #793
This issue is for Project Sorting.
My preferred approach will be to match Todoist sort order. Down the road can possibly change that or allow custom sorting.

**Comment by alanvardy** [comment]
I can't support project sorting by the Todoist order because projects are stored locally in the config file and can be added or removed by the user as desired.

Task sorting now has a `sort` flag and we can add additional options there. Reopen if there is more to discuss!
