### ISSUE TITLE
Add Label Support

### ISSUE THREAD

**Issue by stacksjb** [alanvardy/tod#379]
In "Tod Task Create", add an option after "Select Project" for "Select Labels" with a similar workflow (other than it will need to loop to support multiple labels)

This workflow could then be re-used for "tod task label" request

Will also probably want to add a -l --labels option for "tod task create" which handles a list of label(s) in the @label or @label1,@label2,@label3 format

**Comment by stacksjb** [comment]
Expected workflow:

- Entering "tod task create"
- Prompt for Content - User types in content and enters
- Prompt for Priority - user selects or hits enter
- Project to create in - User selects and hits enter
(Currently runs to this point)
- Label(s) to add - User is presented list of label(s) and can select from list
- Selecting labels adds them to array/list at the top and returns them to the top. Hitting Enter on top/default creates with the selected label(s) (or none if none selected)

**Comment by alanvardy** [comment]
This is already done!

![image](https://github.com/alanvardy/tod/assets/38899847/6d602e66-0e0a-4cf8-bf7b-9355b6c3523f)
