### ISSUE TITLE
Loop "tod project remove"

### ISSUE THREAD

**Issue by stacksjb** [alanvardy/tod#380]
When running "tod project remove", I have to repeat for each one I want to remove. 

If I want to remove a single one, I can already do so by running "tod project remove -p <project>" (or --project)

So when running "tod project remove" I would like the workflow to loop (then the first option can be "exit" or similar to close)

**Comment by alanvardy** [comment]
Does `tod project remove --auto` cover your use case @stacksjb ?

I assume that you are clearing out projects that are not longer in use on Todoist?

**Comment by stacksjb** [comment]
In my case, I am not, though --auto is helpful.

**Comment by alanvardy** [comment]
Add --loop flag to `tod project remove`

**Comment by alanvardy** [comment]
Loop is a protected word, using `repeat` instead in #709

**Comment by stacksjb** [comment]
Ran into this recently, took awhile to find the syntax - noting so I can add to docs
