### ISSUE TITLE
Add "tod project delete" to delete project within Todoist

### ISSUE THREAD

**Issue by stacksjb** [alanvardy/tod#381]
Same workflow as "tod project remove" but would delete project from Todoist (send Project delete API call)

It should first check if project is empty, and if not, either refuse to delete (or requiring some sort of force/confirmation), as API will allow you to delete a project with tasks even if it isn't empty.

**Comment by stacksjb** [comment]
Expected workflow:

- Entering "tod project remove"
- Projects are displayed
- Project to delete/remove is selected
  - If project is empty, it is deleted successfully
  - If project contains tasks, require confirmation
 - Project is deleted in Todoist (And removed from local config, if present)

**Comment by stacksjb** [comment]
Delete API call:

`
$ curl -X DELETE "https://api.todoist.com/rest/v2/projects/2203306141" \
    -H "X-Request-Id: $(uuidgen)" \
    -H "Authorization: Bearer 0123456789abcdef0123456789"
    
    `
    
    Would need to delete (if present) from local config as well, would recommend prompting with a confirmation.

**Comment by alanvardy** [comment]
PR up: https://github.com/alanvardy/tod/pull/922
