### ISSUE TITLE
Add inbox emoji

### ISSUE THREAD

**Issue by stacksjb** [alanvardy/tod#385]
This could be enabled/disabled.

I have emojis on most of my projects, but since you can't customize Inbox, it doesn't display.

Add option to display Inbox as "📥 Inbox" instead of "Inbox"

![image](https://github.com/alanvardy/tod/assets/2865491/e3c43a4a-7ac9-4f09-8db5-73de03ae1182)

**Comment by stacksjb** [comment]
Ok, now I might be overcomplicating this, I think the ideal way to do this would be to split the array into two values, one for "Icon", and one for "Name", (or "Display Name" and "Name").

Then I could display as Icon + name (📥 Inbox) but interact with it still as "Inbox"

As it stands, if I enter "tod project inbox" it doesn't work (since I am not entering the exact name), but if I navigate to the "select project" menu, I get the Icons shown.

**Comment by alanvardy** [comment]
Hm. Right now I am just storing projects as key value pairs, but I could see us improving on this by making it a list of objects in the config. We would need to put it under a new key and figure out the new structure. It's important to me that we make the importing process easy so perhaps keep that simple and have people customize their projects with `tod project edit` later.

The keys for each project could be `name` `display_name` `id` and `is_inbox` off the top of my head

**Comment by stacksjb** [comment]
I'm all ears for any good way to approach this, I think any of the above would work.

**Comment by alanvardy** [comment]
This problem is likely resolved for you now @stacksjb 

Projects are now stored as vector of Project structs, which means that the order in the config is the order in the selection dialog. So you can change the name of the project and it won't change the ordering.
