### ISSUE TITLE
Parse URLs and make clickable in supported terminals (OSC 8)

### ISSUE THREAD

**Issue by stacksjb** [alanvardy/tod#388]
Some items returned by TOD might best be acted upon on the web, such as:
-> A task that is a hyperlink/URL, for example:
`[GitHub - alanvardy/tod: A tiny Todoist command line client in Rust](https://github.com/alanvardy/tod)`
-> Links to file attachments/blobs/binaries (#387) (if attachment -> file_url if included in the response)
-> Task link itself (url in the api response)

These should be formatted/parsed using a CLI utility that makes them clickable when returned in supported terminals, aka OSC 8 (For example list, see https://github.com/Alhadis/OSC8-Adoption/)

Example utilities that do this include:
Rust: https://docs.rs/url/latest/url/ and Terminal-Link (https://crates.io/crates/terminal-link) 
https://docs.rs/terminal-link/latest/terminal_link/ / https://github.com/mainrs/terminal-link-rs

Similar things in other languages
https://cli.r-lib.org/reference/links.html 
https://github.com/sindresorhus/terminal-link

If implemented, a task such as:
`[GitHub - alanvardy/tod: A tiny Todoist command line client in Rust](https://github.com/alanvardy/tod)`

Could be displayed as simply:
[GitHub - alanvardy/tod: A tiny Todoist command line client in Rust](https://github.com/alanvardy/tod)

**Comment by alanvardy** [comment]
I havent tried this yet and it's worth investigating, but there are two things that give me pause about terminal-link:
1. Only works with a couple of terminals
2. Doesn't currently do any runtime checks to see if the links are supported

So this could potentially break the majority of our user's terminals. I don't run MacOS, but if someone who does wishes to implement I can try it out on a variety of Linux terminals to see if any breakages.

**Comment by stacksjb** [comment]
I've dug into this more because one of my workflows involves forwarding attachments into Todoist, so I need to open the link to action the item.

My testing has found that in the several I tested (multiple terminals acrosss Mac and Linux) terminals, OSC8 generally worked as expected. I also specifically tested some that do not support OSC8, and I found that they would display the same text (unclickable) - so I don't expect them to break anything (with the exception that If URLs were hidden entirely (moved into OSC8) then there would be no way to access/see them.

Another library option is the CLI lib (https://cli.r-lib.org/reference/links.html), but I investigated and I don't think that usage of a library is necessarily requried as it is just a formatting of the URLs following the OSC8 specification (see https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda)

The following will test if your terminal supports links - if the link is clickable, it is supported; if it isn't, then it doesn't.

`printf '\e]8;;http://example.com\e\\This is a link\e]8;;\e\\\n'`

I see three stages of potential support:
1) Formatting existing urls so that they are clickable (1, exiting url field that are always URLs, and 2, URLs within tasks etc)
2) Adding URL fields where relevant (such as task_url, attachment_url, etc) (not specifically related ot OSC8)
3) Using OSC8 to hyperlink and format URLs (as in the example above), allowing hiding of URLs and displaying hyperlinks instead

**Comment by stacksjb** [comment]
Testing found that Rust has this crate which automatically will return whether CLI supports hyperlinks or not
https://docs.rs/supports-hyperlinks/latest/supports_hyperlinks/

**Comment by stacksjb** [comment]
It looks like the current struct doesn't have fields currently parsed for the URL fields; do those need to be added before they can be parsed and printed?

**Comment by alanvardy** [comment]
Thats right we need to add the `url` field to the `Task` struct and then serde will deserialize the url.

**Comment by alanvardy** [comment]
This idea was :fire: @stacksjb , thanks for the issue!

**Comment by stacksjb** [comment]
For anyone using iTerm2 and going crazy,  you use "CMD-Click" to tell it to parse URLs on the screen, but you use cntrl-cmd-click to click on an OSC8 link.

now that I figured this out, this is sooo amazing and exactly what I need for my workflow, woohoo!

**Comment by stacksjb** [comment]
Adding note to self to doc this for others.

**Comment by stacksjb** [comment]
This feature was updated/reviewed in 2026 and linkify crate was added for parsing.
