### ISSUE TITLE
Add due date and labels to  "Tod task edit"

### ISSUE THREAD

**Issue by stacksjb** [alanvardy/tod#399]
"Tod task Edit" only returns prompt to edit the name.

It should prompt or allow for:

1. Name
2.  Description
3. Priority
4. Due Date
5. Labels
6. Comments

I don't think all 5 need to be there by default (maybe additional parameters), but definitely 1, 2, and 3

**Comment by alanvardy** [comment]
Look at the way github does it when creating issues

**Comment by stacksjb** [comment]
Ooh nice, I haven't used GH Cli heavily.  I like the way they do it.

Either having extra parameters, or "Edit more, add metadata", or "submit"

**Comment by alanvardy** [comment]
v0.6.17 allows editing of content, description, and priority through multi-select.

Still to do (I'm going to make comments a separate thing):

- [ ] Due Date
- [ ] Labels

**Comment by alanvardy** [comment]
Merging into main
