### ISSUE TITLE
Use a select for setting due dates

### ISSUE THREAD

**Issue by alanvardy** [alanvardy/tod#416]
Split off from: https://github.com/alanvardy/tod/issues/389

> Prompts to select new due date (today, tomorrow, wekeend, next week, postpone (only on recurring tasks; pushes to next recurrence), no date, a manually entered date, or skip)

When scheduling a task, display a select with the following options

- Today
- Tomorrow
- Weekend
- Next Week
- Postpone (only show for recurring, pushes to next recurrence)
- No Date
- Enter Manual Date
- Skip

**Comment by alanvardy** [comment]
This feels like a really long list, can we cut any of the items @stacksjb?

**Comment by stacksjb** [comment]
Good question - those are the options present in the official app.

For rescheduling, we could do a "+ <x> days" (default to 1, allow you to change it, then postpone, no date, skip" 

For setting initial date we probably need more options though.

I had a thought about a possible CLI option the other day, not sure if it is possible - right now scrolling is only up/down on selections, is it possible to add left/right? Then you could have "Postpone", and then arrowing right or left would go through the options.

**Comment by alanvardy** [comment]
This is the rust library we are using: https://crates.io/crates/inquire

In particular, check out the date select here: https://docs.rs/inquire/0.6.2/inquire/struct.DateSelect.html

Maybe for options:

- Natural Language
- Date Picker
- Postpone
- No Date
- Skip

I find natural language to be the fastest for entry so would prefer having it as the first option if possible.

**Comment by stacksjb** [comment]
Thx! Given that we should be able to type any of the options (the selections are only if you're scrolling instead), I think we can just make "natural language" the default (do we even need to display?) and you just type it in. 

So in practice, I could just type "+ x days" or "in 2 days" or "Next weekend", or exact date, or even Postpone

Given that, I think for listed options:
- Natural Language ("In x days") (if we need to display at all)
- Postpone (only for recurring)
- Specific Date -> This could be "Pick Date" and go to date picker
- No Date
- Skip

**Comment by alanvardy** [comment]
Released as part of v0.4.8
