### ISSUE TITLE
Add success/failure sounds

### ISSUE THREAD

**Issue by stacksjb** [alanvardy/tod#442]
I'd like to be able to play a sound on successful task completion, successful task creation, and failure/error to create task.

This might seem like a silly feature, but it's extremely important to me :) Maybe configurable within config?

**Comment by alanvardy** [comment]
Haha, I do use sounds for some of my workflows so I understand. I have my computer ding when the test suite finishes running for example. I'll check into this and agree that it probably should be disabled by default.

**Comment by stacksjb** [comment]
A simple error use case could be to print the bell character on failures, though that's not customizable I think that would be adequate for erro usage (throw the terminal bell).

A larger use case would would be something like:
-> Ability to configure sound for success/creation on/off
-> Ability to configure sound for failure on/of 
-> Ability to specify/configure sound (One possible way would be by specifying path to sound file in config, with default sound(s) included)

There are a few audio playback libraries out there; some more featured than others. The most common one is rodio, but soloud and playback_rs are more compact/basic.

For sound you can easily grab something from a site such as freesound, some success examples:
https://freesound.org/people/Kenneth_Cooney/sounds/609335/
https://freesound.org/people/thisusernameis/sounds/426889/
https://freesound.org/people/GabrielAraujo/sounds/242501/

**Comment by stacksjb** [comment]
I've been playing around with generating some code for a similar wrapper that I will use to automate my workflow with Tod, and here's some example code for audio playback:

Make sure you use tokio (as you already do) so that the audio playback doesn't block the main thread.
```
use rodio::{Decoder, OutputStream, Sink};

pub async fn play_sound(file_path: &str) {
    let file_path = file_path.to_string(); // Clone the file_path to be owned by the closure
    task::spawn_blocking(move || {
        if let Ok((_stream, stream_handle)) = OutputStream::try_default() {
            if let Ok(file) = File::open(&file_path) {
                if let Ok(source) = Decoder::new(BufReader::new(file)) {
                    let sink = Sink::try_new(&stream_handle).unwrap();
                    sink.append(source);
                    sink.sleep_until_end();
                } else {
                    println!("Failed to decode audio file: {}", file_path);
                }
            } else {
                println!("Failed to open audio file: {}", file_path);
            }
        } else {
            println!("Failed to initialize audio output stream");
        }
    }).await.unwrap();
}

```

Then in your thread to play the sound, call

```
                     tokio::spawn(play_sound("soundfile.wav"));
```

**Comment by alanvardy** [comment]
Addressed in this PR: https://github.com/alanvardy/tod/pull/785
Just starting with a terminal bell for now. I will add an issue for setting a filename.
