### ISSUE TITLE
Tot on crates.io status

### ISSUE THREAD

**Issue by you-win** [alanvardy/tod#463]
I'm working on a [config format](https://github.com/totlang/tot) with a parser in Rust called [Tot](https://github.com/totlang/tot-rs).

I noticed that you currently have one of your repos, tot, already [published on crates.io](https://crates.io/crates/tot) but it's labeled as archived ([and also not a library according to docs.rs](https://docs.rs/crate/tot/0.1.2)).

Would you be willing to [transfer the package to me](https://crates.io/policies#package-ownership) so that I can publish my parser under the name "tot"?

**Comment by alanvardy** [comment]
Indeed, please contact crates.io to claim it

![image](https://github.com/alanvardy/tod/assets/38899847/926f18f7-9416-4c1c-969e-aca968842102)

![image](https://github.com/alanvardy/tod/assets/38899847/8e189056-18d8-445b-87ed-fc0b04c13659)

**Comment by you-win** [comment]
Thanks!
