### ISSUE TITLE
GitHub (Linux, Mac, and Windows) section: tarpaulin, build errors (test.sh)

### ISSUE THREAD

**Issue by z3cko** [alanvardy/tod#493]
/In the current version ([6628eb2](https://github.com/alanvardy/tod/commit/6628eb2a4651ab7584100f70f541ef5adccaea8b)) testing does not work on Mac OS X 13.5.

`error: no such command: `tarpaulin``

to add tarpaulin with cargo add fixes this one.

`cargo add tarpaulin`

Still, when running the tests it won't complete testing.

`
Alainas-MacBook-Pro tod % ./test.sh              
  Downloaded crossbeam-deque v0.7.4
  Downloaded tokio-reactor v0.1.12
  Downloaded memoffset v0.5.6
  Downloaded tokio-current-thread v0.1.7
  Downloaded smallvec v0.2.1
  Downloaded tokio-uds v0.2.7
  Downloaded num-traits v0.1.43
  Downloaded slab v0.3.0
  Downloaded tokio-executor v0.1.10
  Downloaded take v0.1.0
  Downloaded log v0.3.9
  Downloaded rand v0.3.23
  Downloaded lock_api v0.3.4
  Downloaded iovec v0.1.4
  Downloaded tokio-fs v0.1.7
  Downloaded crossbeam-queue v0.2.3
  Downloaded smallvec v0.6.14
  Downloaded semver v0.9.0
  Downloaded rustc_version v0.2.3
  Downloaded tokio-timer v0.2.13
  Downloaded net2 v0.2.39
  Downloaded bytes v0.4.12
  Downloaded itertools v0.6.5
  Downloaded futures v0.1.31
  Downloaded mio v0.6.23
  Downloaded rand v0.4.6
  Downloaded parking_lot v0.9.0
  Downloaded tokio-threadpool v0.1.18
  Downloaded tokio-sync v0.1.8
  Downloaded crossbeam-epoch v0.8.2
  Downloaded tokio v0.1.22
  Downloaded two-lock-queue v0.1.1
  Downloaded tokio-proto v0.1.1
  Downloaded crossbeam-utils v0.7.2
  Downloaded tokio-io v0.1.13
  Downloaded parking_lot_core v0.6.3
  Downloaded mio-uds v0.6.8
  Downloaded tokio-tcp v0.1.4
  Downloaded tokio-service v0.1.0
  Downloaded maybe-uninit v2.0.0
  Downloaded semver-parser v0.7.0
  Downloaded tokio-udp v0.1.6
  Downloaded tokio-codec v0.1.2
  Downloaded tarpc-plugins v0.2.0
  Downloaded bincode v0.8.0
  Downloaded thread-pool v0.1.1
  Downloaded scoped-tls v0.1.2
  Downloaded tarpc v0.9.0
  Downloaded tokio-core v0.1.18
  Downloaded 49 crates (1.5 MB) in 1.27s
    Checking log v0.4.19
    Checking cfg-if v0.1.10
   Compiling crossbeam-utils v0.7.2
   Compiling maybe-uninit v2.0.0
    Checking futures v0.1.31
   Compiling semver-parser v0.7.0
    Checking iovec v0.1.4
    Checking byteorder v1.4.3
   Compiling memoffset v0.5.6
    Checking lock_api v0.3.4
    Checking net2 v0.2.39
   Compiling crossbeam-epoch v0.8.2
    Checking mio v0.8.8
   Compiling semver v0.9.0
    Checking mio v0.6.23
    Checking bytes v0.4.12
   Compiling rustc_version v0.2.3
   Compiling num-traits v0.2.15
    Checking tokio v1.28.2
    Checking rand v0.4.6
   Compiling parking_lot_core v0.6.3
   Compiling parking_lot v0.9.0
    Checking mio-uds v0.6.8
    Checking scoped-tls v0.1.2
    Checking tokio-executor v0.1.10
    Checking tokio-io v0.1.13
    Checking tokio-sync v0.1.8
   Compiling either v1.8.1
    Checking tokio-current-thread v0.1.7
    Checking tokio-timer v0.2.13
   Compiling itertools v0.6.5
    Checking rand v0.3.23
    Checking tokio-service v0.1.0
    Checking tokio-codec v0.1.2
    Checking log v0.3.9
    Checking smallvec v0.2.1
    Checking two-lock-queue v0.1.1
    Checking take v0.1.0
    Checking slab v0.3.0
    Checking signal-hook-mio v0.2.3
    Checking thread-pool v0.1.1
    Checking lazy_static v0.2.11
    Checking smallvec v0.6.14
    Checking crossbeam-queue v0.2.3
    Checking crossterm v0.25.0
    Checking crossbeam-deque v0.7.4
   Compiling tarpc-plugins v0.2.0
error[E0557]: feature has been removed
 --> /Users/parasew/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tarpc-plugins-0.2.0/src/lib.rs:1:12
  |
1 | #![feature(plugin_registrar, rustc_private)]
  |            ^^^^^^^^^^^^^^^^ feature has been removed
  |
  = note: a __rustc_plugin_registrar symbol must now be defined instead

error[E0463]: can't find crate for `rustc_plugin`
 --> /Users/parasew/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tarpc-plugins-0.2.0/src/lib.rs:4:1
  |
4 | extern crate rustc_plugin;
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate
  |
  = help: maybe you need to install the missing components with: `rustup component add rust-src rustc-dev llvm-tools-preview`

error[E0463]: can't find crate for `syntax`
 --> /Users/parasew/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tarpc-plugins-0.2.0/src/lib.rs:5:1
  |
5 | extern crate syntax;
  | ^^^^^^^^^^^^^^^^^^^^ can't find crate

error: cannot find attribute `plugin_registrar` in this scope
   --> /Users/parasew/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tarpc-plugins-0.2.0/src/lib.rs:192:3
    |
192 | #[plugin_registrar]
    |   ^^^^^^^^^^^^^^^^
    |
    = note: `plugin_registrar` is in scope, but it is a function, not an attribute

error[E0554]: `#![feature]` may not be used on the stable release channel
 --> /Users/parasew/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tarpc-plugins-0.2.0/src/lib.rs:1:1
  |
1 | #![feature(plugin_registrar, rustc_private)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Some errors have detailed explanations: E0463, E0554, E0557.
For more information about an error, try `rustc --explain E0463`.
error: could not compile `tarpc-plugins` (lib) due to 5 previous errors
warning: build failed, waiting for other jobs to finish...

`

**Comment by alanvardy** [comment]
Hey, thank you for the issue!

I have a friend with a MacBook who was able to reproduce this, please feel free to open up a PR with any steps you come up with to resolve, otherwise I hope to get working on this soon.

Steps needed:

- Add setup instructions to README under Contributing
   - `cargo install cargo-tarpaulin`
   - `rustup component add rust-analyzer`
   - ??? for MacOS

**Comment by alanvardy** [comment]
Added instructions in this PR: https://github.com/alanvardy/tod/pull/495

Basically, instead of `cargo add tarpaulin` which attempts to add the tarpaulin library as a dependency to your cargo toml, you want to run `cargo install cargo-tarpaulin` which adds the tarpaulin CLI application.

Thanks again!
