### ISSUE TITLE
Improve configuration documentation

### ISSUE THREAD

**Issue by alanvardy** [alanvardy/tod#496]
https://www.reddit.com/r/todoist/comments/12nkfe7/comment/jnkateu/?utm_source=share&utm_medium=web2x&context=3

Add a configuration section and describe all the fields, possible values, and what they do

**Comment by stacksjb** [comment]
I'm happy to assist with this!

**Comment by alanvardy** [comment]
That would be great! I have an initial version on `main` but it may need some polishing/organization

**Comment by alanvardy** [comment]
Good enough for now
