### ISSUE TITLE
Add nosection flag to task create

### ISSUE THREAD

**Issue by TorgeirCook** [alanvardy/tod#537]
When I try to add a task to a list that has sections, I'm forced to choose a section.

**Comment by alanvardy** [comment]
Hi @TorgeirCook and thank you for the issue.

I can add a flag to the `tod task create` called `nosection` that will disable section choosing for that invocation.

I will also add a configuration option in `tod.cfg` that can globally disable section choosing.

Would that meet your needs?

**Comment by TorgeirCook** [comment]
Thanks for the quick response @alanvardy!

I like the options to enable and disable sections with the flag and config. Can you also add a option in the section option list, something like "no section"?

Cheers!

**Comment by alanvardy** [comment]
Alright, breaking this up over a few tickets:
- [Add ability to choose no section](https://github.com/alanvardy/tod/issues/445)
- [Add nosections boolean to Config](https://github.com/alanvardy/tod/issues/538)
- This ticket is for add the --nosection flag

**Comment by alanvardy** [comment]
This issue is resolved on main, will release a new version when the other 2 are complete :+1: 
https://github.com/alanvardy/tod/pull/539

**Comment by alanvardy** [comment]
v0.5.2 is released to crates.io and AUR
