### ISSUE TITLE
Describe quickadd syntax

### ISSUE THREAD

**Issue by TorgeirCook** [alanvardy/tod#559]
Is it possible to include task description when adding tasks with quickadd? I wasn't able to find the todoist docs https://todoist.com/help/articles/task-quick-add.

**Comment by stacksjb** [comment]
Yes - use the //description syntax.

**Comment by stacksjb** [comment]
@stacksjb this is a good thing to add to documentation as it's not currently mentioned.

**Comment by alanvardy** [comment]
Since quickadd is the most used feature we can describe some of the todoist syntax in the docs and link to one of their pages for more info.

**Comment by alanvardy** [comment]
Done!

**Comment by stacksjb** [comment]
You're welcome to swipe my quickadd documentation for the workflow (https://github.com/stacksjb/AlfredTodWorkflow/edit/main/README.md)

### Examples
* "Respond to Jim's marketing email" : creates a new task in the Inbox titled "Respond to Jim's marketing email"
* "Clean my room on tuesday at 1pm p2" : creates a task named "Clean my room" due on Tuesday at 1pm, with Priority of 2
* "Ship UPS Package #eBay @errands p2 tomorrow" : creates a task in the eBay project, anerrands label, priority of 2, due tomorrow.
* "Purchase apples //Granny Smith" : creates a task in the Inbox named "Purchase apples" with a description of "Granny Smith"

**Comment by alanvardy** [comment]
I think I will!

**Comment by alanvardy** [comment]
Done, thank you
