### ISSUE TITLE
Order tasks by priority after getting from filter

### ISSUE THREAD

**Issue by alanvardy** [alanvardy/tod#572]

**Comment by alanvardy** [comment]
Done

**Comment by stacksjb** [comment]
To clarify on this PR, this was simply to sort the tasks by the defined priority used elsewhere (see https://github.com/alanvardy/tod/issues/3 or https://github.com/alanvardy/tod/issues/354) correct?

(Just wanted to clarify this is by the hardcoded "priority", not Todoist (p1/p2/p3)

**Comment by alanvardy** [comment]
Correct, the hardcoded "internal" priority that we will soon allow people to customize :+1:
