### ISSUE TITLE
Priorities reversed when adding task

### ISSUE THREAD

**Issue by Susensio** [alanvardy/tod#579]
When I do `tod task create`, when it prompts for priority, priorities are saved in reverse. That is,

```
if I select   --->   i get
P4                     P1
P3                     P2
P2                     P3
P1                     P4
```

This only happens on interactive prompt. When using `tod task create --priority <NUM>` it works as expected

**Comment by alanvardy** [comment]
Hello @Susensio , thank you for the bug report! Fix coming soon :+1:

**Comment by Susensio** [comment]
Np, tried to find the bug in the source code but i couldn't, I'm pretty new to rust.
Great app btw! Very well though cli!

**Comment by alanvardy** [comment]
v0.5.7 is released on AUR and Crates.io, thanks again and please let me know if you have any further issues or requests!
