### ISSUE TITLE
BUG: Tasks with fixed (non-floating) timezone that are non tz-date compatible crash

### ISSUE THREAD

**Issue by stacksjb** [alanvardy/tod#620]
While testing #592 I discovered the query gave me an error

`
/Users/.../Library/Application Support % tod task list -f "tod | overdue"
thread 'main' panicked at /Users/*/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tod-0.5.7/src/time.rs:69:46:
called `Result::unwrap()` on an `Err` value: "'GMT -7:00' is not a valid timezone"
`

**Comment by stacksjb** [comment]
Queries using a non-date based filter (i.e. label @home) succeed; but any involving date-based filters (due, overdue, today, <x> days) etc fail.

**Comment by alanvardy** [comment]
I don't have this error, I suspect that it could be related to your config?
![image](https://github.com/alanvardy/tod/assets/38899847/91b64aaa-b9e9-4f93-8ae0-87662f95bf70)

My timezone in the config is Canada/Pacific, what is yours?
![image](https://github.com/alanvardy/tod/assets/38899847/40e9b239-d1e4-429e-b2ab-563fdc7b468b)

**Comment by stacksjb** [comment]
US/Mountain gives same error that " "'GMT -7:00' is not a valid timezone"

I deleted and re-set up and got the same error - I'm using a valid one given from the library.

It seems like it should be getting "US/Denver" and not "GMT - 7:00", but somewhere the tz is being converted to string instead?

**Comment by stacksjb** [comment]
Also (maybe) related, several functions were deprecated/modfied so maybe some tweaks need to be made? 
https://docs.rs/chrono/latest/chrono/struct.DateTime.html

**Comment by stacksjb** [comment]
One of the last apps I used to work through tasks one at a time (Flowist.app) appears to be shut down, which is great because I can move my final workflows into Tod (I'm excited!)

...Except I'm still getting this error :(

Here's the backtrace:

```
> Enter a filter:  @Morn & (due today | overdue | no due date)
⠆ Querying APIthread 'main' panicked at /Users/j/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tod-0.5.7/src/time.rs:69:46:
called `Result::unwrap()` on an `Err` value: "'GMT -7:00' is not a valid timezone"
stack backtrace:
   0: rust_begin_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/result.rs:1649:5
   3: tod::tasks::Task::datetimeinfo
   4: tod::tasks::Task::value
   5: core::slice::sort::insertion_sort_shift_left
   6: tod::filters::process_tasks
   7: tod::filter_process
   8: tod::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by stacksjb** [comment]
This filter works correctly

`➜  ~ tod filter process -f "@Work & (due today | overdue | no due date)"`

**Comment by stacksjb** [comment]
Makes no sense to me why a single filter called "Morn" would break things. 

I tried renaming to "Morning", same error
```➜  ~ tod filter process -f "@Morning"
⠇ Querying APIthread 'main' panicked at /Users/jesse/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tod-0.5.7/src/time.rs:69:46:
called `Result::unwrap()` on an `Err` value: "'GMT -7:00' is not a valid timezone"
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace```
My filter named "Mental" works fine.
```
➜  ~ tod filter process -f "@Mental"
Intermittent Fast
! 2023-10-01 ↻ ev 1st @ Mental
```

Would someone else try creating a filter named "Morn" or "Morning" and see if they get same issue?

**Comment by stacksjb** [comment]
My best theory at the moment is that it is related somehow to some content within a task within my filter set, because:

1) If I rename the filter, the error follows
2) If I try a different filter, the query works correctly
3) If I try the filter query with a blank filter (either a filter that does not exist, or a filter that doesn't have tasks), I don't get the error.

**Comment by stacksjb** [comment]
FIGURED IT OUT. 

Tod breaks if you have tasks with Task Durations.

Recently, Todoist introduced native Task Durations (https://todoist.com/help/articles/set-a-task-duration-L1kYkZv8d). This is typically set on a task with the language of "Due at <x> time for <x> duration.

I had a task set with a duration of "for 15m"

**Comment by stacksjb** [comment]
@alanvardy requesting your help to (at minimum) not crash/break when pulling tasks with task duration. 

I will reach out to Todoist API team and see what I can find out about creation and editing of tasks with duration; will document further work there on #633

**Comment by stacksjb** [comment]
Ok... after further testing, I spoke too soon yet again. Sorry 🙈. 

This has nothing to do with task durations (although we do need to add support and I've reached out to Todoist API team...)... 

This error happens on tasks set with a fixed/manual timezone as opposed to a floating timezone is set, when the timezone in the task data is non tzdata-compatible (see https://todoist.com/help/articles/set-a-fixed-time-or-floating-time-for-a-task-YUYVp27q)

To fix this, if a task is returned with a due timezone parameter (is only returned if an exact due time is set; otherwise it is NOT returned).

To reproduce:
1) Set your Todoist timezone to a non-tzdata compatible timezone, such as "GMT-7"
![image](https://github.com/alanvardy/tod/assets/2865491/be96d9a7-2bb3-4f9a-8b6c-be2edf1ea615)

2) Create a task with a fixed due time
![image](https://github.com/alanvardy/tod/assets/2865491/c21d5be4-6dcb-4629-a214-be25b846b279)

Tod will then crash retrieving those tasks anywhere they are received (projects, list, prioritize, filters, etC).

I'm 100% positive I changed this manually because I have some tasks created via API that need fixed due timestamps (due at that exact time), but I'll investigate changing this back and fixing it in my code (see what I break).

@alanvardy would you add to the documentation on the main page a known issue and/or setup step that your Todoist profile timezone and your TOD Config timezone MUST match exactly? (I will see if this is something that can be pulled or checked, but if not, it appears that changing to a tz-data compatible one works)

**Comment by alanvardy** [comment]
Wow, thanks for the investigation. I'll take a closer look at this tomorrow morning and come up with some ideas. I would prefer to not crash... perhaps I can find a way to emit a clear error message or fall back gracefully to config.

**Comment by stacksjb** [comment]
Part of the issue is that this is a per-task setting - so if a user were to encounter this, simply setting their profile timezone back won't fix the issue retroactively (I had to go through my task DB and change the timezones manually back on each task which was set the UTC Offset timezone instead of a tzdata one).

**Comment by alanvardy** [comment]
v0.5.8 is released with this PR: https://github.com/alanvardy/tod/pull/640

I am now parsing the offset timezones as well and added a test, can you pull down the latest version and see if you can reproduce the error?
