### ISSUE TITLE
Add missing descriptions to commands 

### ISSUE THREAD

**Issue by stacksjb** [alanvardy/tod#621]
(Good First Issue)

A few of the main commands (such as task, project, filter, and version on the main "tod" entry) have no details. Need descriptions added.

![image](https://github.com/alanvardy/tod/assets/2865491/1eb543b8-230e-4919-b312-4c48620d9a5b)

**Comment by stacksjb** [comment]
In particular, I'm a bit confused on the usage of "filter" command - doesn't it duplicate the "-f" usage in other areas?

**Comment by alanvardy** [comment]
![image](https://github.com/alanvardy/tod/assets/38899847/a3980e6b-c734-4cdd-a2c4-5401f3742646)
Fixed!
