### ISSUE TITLE
Add `config reset`

### ISSUE THREAD

**Issue by stacksjb** [alanvardy/tod#622]
(Good first issue)

I would like to see a "setup" or "config" menu option, which provides the options for things that are done on an as-needed basis.

-Reset to defaults (delete config file and exit)
-Import projects (import projects from Todoist into local config)
-Check for updates/version info

In the future doing things such as 
-Import/save favorites/filters

**Comment by stacksjb** [comment]
There are several "tod config" issues that can be included here
#315 #316 #317 #318

**Comment by alanvardy** [comment]
We have project importing and version checking implemented, just need to reset config now.

**Comment by alanvardy** [comment]
Done, and on main
