### ISSUE TITLE
Redesign Tod API

### ISSUE THREAD

**Issue by alanvardy** [alanvardy/tod#623]
In particular, I'm a bit confused on the usage of "filter" command - doesn't it duplicate the "-f" usage in other areas?

_Originally posted by @stacksjb in https://github.com/alanvardy/tod/issues/621#issuecomment-1922281774_

**Comment by alanvardy** [comment]
![image](https://github.com/alanvardy/tod/assets/38899847/366da5f9-e8f7-4341-a5b0-83452c0df1d3)

Here is the current Tod API

**Comment by alanvardy** [comment]
![image](https://github.com/alanvardy/tod/assets/38899847/e74a1000-3852-4fc6-abd7-a67003d26bde)

I need the filter sub command for new filter features that I am creating, and I need a subcommand for operating across multiple tasks but I'm not sure what to name it. Tasks? List? I would prefer it to be the name of a resource in order to match With the rest of the sub commands. What are your thoughts?

**Comment by stacksjb** [comment]
Another detail that might help: I think it is helpful to differentiate (especially for those who have a GTD-style workflow, as I do) between commands for viewing/executing/completing tasks and those for labelling/processing/working with tasks.

**Comment by alanvardy** [comment]
![image](https://github.com/alanvardy/tod/assets/38899847/0b48e711-1adb-4979-a920-2e9724e33c1c)

Does this image make more sense?

**Comment by stacksjb** [comment]
for completeness, the only item missing from the image above is the 'config' section, where things such as setup, set-timezone, set-token, set-spinners, clear, and other config-related items would go (#316 #317 #318 etc)

**Comment by alanvardy** [comment]
Currently working on this

- [ ] project list
- [ ] project remove
- [ ] project rename
- [ ] project empty
- [ ] project import
- [ ] task create
- [ ] task edit
- [ ] task list
- [ ] task next
- [ ] task complete
- [ ] list label
- [ ] list process
- [ ] list prioritize
- [ ] list schedule
- [ ] version check

Create tickets for:
- [ ] filter create
- [ ] filter list
- [ ] filter delete
- [ ] config ...

**Comment by alanvardy** [comment]
Done!
