### ISSUE TITLE
Add color/icons/flags to Priority

### ISSUE THREAD

**Issue by stacksjb** [alanvardy/tod#638]
The None/Low/Medium/High priority icons currently are like this:
> NONE (P4)
  LOW (P3)
  MEDIUM (P2)
  HIGH (P1)
  
  It would be nice if, on a terminal that supports it, colors were added to match with the official app/format. Either of these options would work:
  
  NONE (P4) ⚫
  LOW (P3) 🔵
  MEDIUM (P2)  🟠
  HIGH (P1) 🔴
  
(using emojis.. hmm, not a huge fan)

or using ANSI terminal colors and/or using the flag/penant icon, would look more like this (my favorite)
![image](https://github.com/alanvardy/tod/assets/2865491/bd664f15-c7e3-4edf-9271-e764bfc318e1)

**Comment by stacksjb** [comment]
if we wanted to get reaaaally fancy, we could leave off the flag icon and the color, and only highlight the flag on the row selected... but that kind of defeats the purpose of showing the three colors (which helps me more quickly pivot to the exact priority needed without having to read them), unless we did option two.

**Comment by alanvardy** [comment]
PR going up 
![image](https://github.com/user-attachments/assets/81e81a71-6f9d-49d4-8ffd-2214a87610ff)
