### ISSUE TITLE
Add "Delete" to project empty/assign commands

### ISSUE THREAD

**Issue by stacksjb** [alanvardy/tod#639]
Sometimes when I am clearing out Task Inbox, I find tasks I don't want to complete or work on, and I simply want to delete them - currently I just "complete" them, though that inflates my stats, so I'd rather just delete them.

**Comment by alanvardy** [comment]
Should be a light lift.

**Comment by stacksjb** [comment]
Add to "tod filter process" and "tod task [delete]"
