### ISSUE TITLE
Add task count remaining to "tod filter process"

### ISSUE THREAD

**Issue by stacksjb** [alanvardy/tod#643]
Similar to "Tod task next" , print the "45 task(s) remaining" (or however many) when using "Tod filter process" 

(Because I use filters for my actions, I use "Tod filter process" to get through my workflow instead of "Tod task next", but it's missing feature parity with the "Tod task next")

**Comment by alanvardy** [comment]
Added in this PR: https://github.com/alanvardy/tod/pull/648 :+1:

**Comment by alanvardy** [comment]
(let me know what you think of the formatting)

**Comment by stacksjb** [comment]
Look great - thanks!
