### ISSUE TITLE
Asynchronous/background processing

### ISSUE THREAD

**Issue by stacksjb** [alanvardy/tod#644]
It would be really nice if for multiple request work (such as when I am doing "Tod project empty"), the API requests could happen asynchronously in the background, so I could move through project assignment more quickly.

This would allow me to hit enter, project, assign, enter, etc, without the ~5s wait for API request to complete.

This would require batching the API requests in the background, pausing interaction when a limit is reached (say, >5 API requests pending), and could increase the likelihood of hitting Todoist rate limiting API requests (though the limit is high - 450 requests in a 15 minute period, which works out to ~1 request every 2 seconds constantly for 15 minutes)

**Comment by stacksjb** [comment]
I've done some basic research, and it sounds like the most common async library used in Rust is Tokio (https://tokio.rs)

Initial prep work for moving to an asynchronous code would probably be to set up the code with batching, separating the function for API queries/updates and the UI).

For example, currently workflow is effectively (for one example)
`
List task
Select destination project
Execute API query
LIst task
Select destination project
Execute API query,
etc
`

An example workflow to move to async would be
`
list task
select destination project
list task
add update to array to execute
select destination project
(and so forth)
(Once array list reaches a size, say 10, or all are completed, etc, run the API updates all at once sequentially).
`

Then once you have moved to that format, such that queries are added to a queue, then batch executed, (at any time, or once queries reach 5, etc), moving to async becomes easier because you can simply replace the batch function (that you are executing at a set time) with an async function that happens transparently in the background.

**Comment by alanvardy** [comment]
I am merging in the PR right now for `list process` and have tickets for the rest. Awesome improvement, thank you!

I ended up using Tokio and spawning tasks (green thread/background jobs) so they start executing right away and don't block the main thread. If, for some reason, they are taking a while, they will block at the end until they finish processing.

**Comment by stacksjb** [comment]
This is amazing! works so well!

**Comment by stacksjb** [comment]
I just completed clearing my inbox in minutes using this - faster than my previous method. Thank you!!
