### ISSUE TITLE
Label Workflow Updates

### ISSUE THREAD

**Issue by stacksjb** [alanvardy/tod#645]
A few updates to Labels would make this process work perfectly for my workflow:
1) I usually label tasks by Project, not by filter, so it's an extra step to write a filter. Adding "Tod project label" would address this.
2) It would be ideal to have my list of Labels in the Config instead of manually entered each time at run time (so I could select from a preconfigured list), possibly imported from Todoist

**Comment by alanvardy** [comment]
The second item is covered by: https://github.com/alanvardy/tod/issues/592

For the first, it will be included in the new tod API. https://github.com/alanvardy/tod/issues/623
