### ISSUE TITLE
Add verbosity

### ISSUE THREAD

**Issue by stacksjb** [alanvardy/tod#655]
Troubleshooting issues with verbosity (-v --verbose) and would love some more verbosity levels. 

Would we be able to expand with -v, maybe -vv?

Level 1 - print requests and IDs numbers (task, project, label)
Level 2 - print full requests & response (full json) & status codes

**Comment by alanvardy** [comment]
Really cool idea, would help a ton with debugging

**Comment by alanvardy** [comment]
We have a verbose flag at root now, I am comfortable with 1 level until more becomes necessary. It's logging requests and json returned, and we can add more as needed :+1:
