### ISSUE TITLE
Quickadd fixes

### ISSUE THREAD

**Issue by stacksjb** [alanvardy/tod#711]
Thanks for the improvements @alanvardy  - it will take a bit of work to adjust but appreciate the changes!

Two notes:
1) The change in syntax from "tod -q" to "tod t q -c" broke my scripts - easy fix but adjusted to use "tod t q -c <CONTENT>". 

Would you please let me know about syntax changes/deprecations in the future?

2) The syntax for "tod t q -c" doesn't seem fully flushed out - if I run "tod t q" it errors, instead of prompting for the content.
I think typing "tod t q" should prompt for task input (same as "tod task create" does) on one line.

Thx again!

**Comment by alanvardy** [comment]
> Would you please let me know about syntax changes/deprecations in the future?

I wasn't sure about how close you were tracking, should I @ you on relevant PRs? For changes to anything or just a subset? I definitely would like to keep you in the loop.

>The syntax for "tod t q -c" doesn't seem fully flushed out - if I run "tod t q" it errors, instead of prompting for the content.
I think typing "tod t q" should prompt for task input (same as "tod task create" does) on one line.

My bad, I missed this one. Will issue a fix today :+1:

**Comment by alanvardy** [comment]
Thanks for the issue and sorry for the breakage. `content` is now an optional flag for `quick-add` as of release `v0.6.2` that was just released.

**Comment by stacksjb** [comment]
As far as informed - just any breaking changes (changes which remove existing CLI commands). 

I like the new format! I just expected -q to still work. Ideally, the best method would be to either deprecate prior to removal, or notify.  Either way I got it fixed and we're good - thanks again!

**Comment by alanvardy** [comment]
I totally agree with the deprecation warning, I'm going to get this done more professionally next time.
