### ISSUE TITLE
Make project empty async

### ISSUE THREAD

**Issue by alanvardy** [alanvardy/tod#721]

**Comment by alanvardy** [comment]
PR up

**Comment by alanvardy** [comment]
@stacksjb `list process` and `project empty` are now async on `v0.6.3` Let me know what you think!

**Comment by stacksjb** [comment]
This is beautiful and works SO well!! I was elated when I saw this. Thank you so much!

It would be good to note that generally async (nonblocking) is preferred, but there are probably some specific use cases that should remain blocking - generally those where you are working on a single item.

The main use case that comes to mind is "tod task next", "tod task complete", or tod task quick-add - in particular my current extension that adds a task needs to get an immediate result/response back that it was successful or failed.  (This could be handled with a specific flag though - I could see a "bulk add" possibly down the road?)

**Comment by alanvardy** [comment]
I 100% agree. It will just be for the cases where we are trying to process items rapidly, as we get less feedback this way.
