### ISSUE TITLE
Allow the usage of a pre-defined list of labels

### ISSUE THREAD

**Issue by stacksjb** [alanvardy/tod#732]
When running 'tod list label', I have to manually specify a full list of labels each time.

We should instead have a list of labels locally in the config (could be imported, created, etc) that can be selected from.

No need to change existing label functionality - simply append (for that execution) the labels provided to the local list.

**Comment by alanvardy** [comment]
`list label` now pulls your labels from the API on `main` when no labels are specified. Does this meet your needs? Please reopen if not!
