### ISSUE TITLE
Sign Commits

### ISSUE THREAD

**Issue by stacksjb** [alanvardy/tod#768]
I have GitHub Vigilant Mode enabled for my signed commits (https://docs.github.com/en/authentication/managing-commit-signature-verification/displaying-verification-statuses-for-all-of-your-commits), so my commits are signed. 

@alanvardy would you be able to sign your commits? Otherwise I can disable - commits will be marked as partially validated/unvalidated otherwise.

**Comment by stacksjb** [comment]
You may want to consider enabling signed commit branch protection

![image](https://github.com/alanvardy/tod/assets/2865491/641e7db2-1ead-49cb-93b0-a9c5df57d41e)

**Comment by alanvardy** [comment]
I double checked and my commits are currently signed

![image](https://github.com/alanvardy/tod/assets/38899847/d0181def-02ca-49fb-b0fb-07203f4de2d1)

My initial instinct is to check off the `Required signed commits` box, but then I wonder if it would create an unreasonable barrier to contributors. I read [this article](https://dlorenc.medium.com/should-you-sign-git-commits-f068b07e1b1f) and think this feature may have only marginal benefits.

```
Unless you’re really worried about the impersonation angle, I don’t really recommend signing git commits for most people. Take care of your basic account hygiene with MFA and hardware tokens, and that’s plenty for most people. 
```

You have more knowledge in this area, can you convince me that the benefits are worth the drawbacks?

**Comment by stacksjb** [comment]
Thx for your comments. I was investigating this because my commits to the repo were showing up as "Unverified" in the release commit history

![image](https://github.com/alanvardy/tod/assets/2865491/b384d036-616a-4d3b-9a84-3bebd94a9601)

This is because I have both signed commits and vigilant mode enabled. I think this is because after my PR was merged, I clicked the button to sync the commits, but then it was left ahead; I clicked the "discard commits" since they had already been merged and now they are unverified. 

-> I think I've figured out how I was supposed to rebase (I should have done a "hard reset" instead); Would you make a temp branch I can test commit against and validate? 

Doesn't look like I can do anything about that notice for now (other than possibly disable vigilant mode).

**Comment by stacksjb** [comment]
One last comment - you may want to consider creating a "dev" and a "release" branch, with all code being pushed to dev and releases going to the release. 

That way you can require code signing for the "release" branch, and require all PRs go to the "dev" branch where it isn't required. 

In any case this can be closed once you make a decision on what to do - My preferred recommendation would be to require codesigning on a production branch with vigilant mode enabled (particularly one that releases are generated from), but I'll leave that up to you since it's a github wide setting that would affect all repos you own/manage and other external ones you commit to.

**Comment by stacksjb** [comment]
Validated that this is good - thx

**Comment by stacksjb** [comment]
A random side note when i was poking with code today - if you use Graphite Dev, you need to have the Graphite commit signing key (https://app.graphite.dev/settings/commit-signing) added to your Github profile.

**Comment by alanvardy** [comment]
Thank you, I added the Graphite GPG key 👍 

Does everything else look good for you now?

**Comment by stacksjb** [comment]
Looks the same as before (presumably you have to enable vigilant or similar to get the icon on releases), but I was able to validate they are signed.
