### ISSUE TITLE
Issue templates

### ISSUE THREAD

**Issue by stacksjb** [alanvardy/tod#775]
I'd like to enable Issue and PR Templates ([see https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository and ](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests))

(@alanvardy I don't have access to do so, but once enabled, I can submit a PR with the appropriate templates)

Questions:

For issues, I see a few categories:

1. Bug (would want debug logs, version info, expected/actual result, etc)
2. Feature request (would want use case, dependencies, etc)
3. Documentation (for workflows, docfixes, etc)
4. Other (for other issues or comments)

For PRs, is there any specific code review or templates we would require or any attestations?
For example, we have the automatic CI requirements, are those enforced or should be required? Do we require all conversations to be resolved (I think we should)?

Thx!

**Comment by alanvardy** [comment]
Do you have access now?

**Comment by stacksjb** [comment]
Not yet, but I will submit a PR with the appropriate templates and I *think* that should enable them.

**Comment by alanvardy** [comment]
PR up :+1:
