### ISSUE TITLE
Predefined "get task next"

### ISSUE THREAD

**Issue by stacksjb** [alanvardy/tod#777]
As I've mentioned in other places (https://github.com/alanvardy/tod/issues/355#issuecomment-1982414379), my workflow involves cataloging, processing, and then working through tasks in a set of predefined filters.

I would love the ability to define (in config) somewhere a list of predefined filters to work through, and Tod would automatically:
1) Pull the first task in the list, sorted based on the defined config priority & grouping
2) Give me the option to complete, postpone/reschedule, skip task
3) Tell me how many are remaining
4) Automatically move onto the next when ready (with breaks in between groups - similar to a pomodoro).

I'm not sure if this is best included in the existing "tod task next" (perhaps "auto next"), or a seperate command - personally I think it would be pretty cool to have this as a specific separate command and brand it something like "Work!" or "complete-tasks"

**Comment by alanvardy** [comment]
I've put some thought into it and think that this is out of scope for the project. Some alternatives that might work for you:

- Time blocking with an app like Akiflow
- a shell script with `sleep` , `tod task next`, and `tod task complete`.

Feel free to reopen if you think that there is some more context I could use.

**Comment by stacksjb** [comment]
I'm doing this basically in my CLI_Menu so I think I'm covered. 

I do think this is worth looking at in the future, since it's basically just chaining what is already done together into multiple steps. But it depends on how deeply I take it - i agree it could easily be out of scope, especially if I need to start coding in something like 'breaks after <x> tasks'
