### ISSUE TITLE
Create a CONTRIBUTING.md

### ISSUE THREAD

**Issue by alanvardy** [alanvardy/tod#781]
https://github.com/nayafia/contributing-template

Take a look at how the pros do it, and come up with our own flavour. We want people to open up issues before opening PRs.

**Comment by stacksjb** [comment]
Agree! Definitely something I want to add to documentation.

**Comment by stacksjb** [comment]
SEe also https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-code-of-conduct-to-your-project 
https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors
https://docs.github.com/en/communities

**Comment by alanvardy** [comment]
Done
