### ISSUE TITLE
Add "tasks completed today" count

### ISSUE THREAD

**Issue by stacksjb** [alanvardy/tod#791]
Official client has a daily tasks completed, not sure if we can use that (might be preferable) or if will need to track/store locally (all the more reason to just use tod 😆)

Will check into API.

**Comment by stacksjb** [comment]
Confirmed with Todoist support that this is available through the activity logs

 [https://developer.todoist.com/sync/v9/#get-activity-logs](https://www.google.com/url?q=https://developer.todoist.com/sync/v9/%23get-activity-logs&source=gmail-imap&ust=1718051071000000&usg=AOvVaw3gKYkgF-KjXof4NY2X8BqC) endpoint and programmatically filter/count the tasks where the object_type is item, event_date is today's date and the event_type is completed.

However, since that requires extra work, I think tracking completed count locally would be more than adequate in most cases.

**Comment by alanvardy** [comment]
Are we thinking of making this a specific command?

I.e. `tod stats completed-today` or something similar?

**Comment by stacksjb** [comment]
We certainly could add a whole stats implementation, but that seems like a further down the road thing, might require maintaining some sort of local DB or log tracking.

My initial thought was simply a "completed" total printed as you check off, that is either stored per runtime or per day as you complete tasks - probably add to the same line as the task(s) remaining

**Comment by alanvardy** [comment]
Already on released, let me know what you think
![image](https://github.com/user-attachments/assets/e53e5d6d-7766-4263-ad1b-eb509423d1d9)
