### ISSUE TITLE
Add pre-commit format checks

### ISSUE THREAD

**Issue by stacksjb** [alanvardy/tod#807]
Post-CI catches most formatting and Clippy errors, but those could be easily caught as part of a pre-commit script.

I've usually managed precommit git hooks manually in the past (powerful but painful), which I'm happy to do, but there's a great rust tool for rust apps (https://github.com/swellaby/rusty-hook) which does it for you - I've added it to the rusty-hook branch and submitted a PR.

Adds a single dependency for dev but no changes to running the app. Automatically checks formats and will block submit/push with the applicable error if it fails.

**Comment by stacksjb** [comment]
See https://github.com/alanvardy/tod/pull/808

**Comment by stacksjb** [comment]
Alternatively could use something like pre-commit (https://pre-commit.com/) which does work well (I'm using that in other projects) but why would we use something not written in native Rust for an awesome rust program? 😁

**Comment by alanvardy** [comment]
Done!
