### ISSUE TITLE
Add a space between items when processing

### ISSUE THREAD

**Issue by alanvardy** [alanvardy/tod#827]
tod list process needs a space between entries when processing

**Comment by rvbcldud** [comment]
I'd be happy to work on this! By space, do you mean newline?

After some brief investigation. It seems that when you process using a filter, there is a newline between each entry. When using process with a project, there is not. Would you like the former to look like the latter. Let me know!

**Comment by alanvardy** [comment]
Yes! I do mean a newline and thank you for finding the difference between the two. Yes, please feel free to take this issue :+1:

**Comment by rvbcldud** [comment]
Proposed change implemented in #833
