### ISSUE TITLE
Add postpone functionality

### ISSUE THREAD

**Issue by stacksjb** [alanvardy/tod#843]
On tasks that are recurring, the official todoist Client offers "Reschedule" and "Postpone"

The scheduling feature from #634 / #744 works very well for rescheduling! Thanks!

However if I simply want to simply postpone, I realized I don't actually need to set a new date or do any calculation logic - if I just resubmit with the due.string, Todoist will automatically take care of the rest as it re-calculates the due.date from the due.string.

So adding a "Postpone" option only for tasks that are recurring in the "list process" and "task next" options would be helpful. Alternatively (not sure if it can be done with date picker, but I like how slick this would be) instead of adding another calendar calculation option, it could just be a shortcut/hotkey on the schedule calendar for recurring (so instead of `[arrows to move, []{} move months and years, enter to select]`, it could be `[arrows to move, []{} move months and years, enter to select, P to postpone]`

This means I don't have to actually do any logic or even bother with using the "starting on" syntax; I can just take a task due "every day", for example, and set it to again be due "every day", and todoist will automatically move it to the next "day" (the same logic would work for "every 30th", every 2nd etc)

**Comment by stacksjb** [comment]
A reminder this is only for recurring tasks (those with due.is_recurring = yes)

**Comment by alanvardy** [comment]
This is currently covered with existing functionality. Rescheduling a recurring task will preserve the recurring nature and just set the next occurrence, seen in this code from line 192 in `todoist.rs`

```rust
/// Update due date for task using natural language
pub async fn update_task_due_natural_language(
    config: &Config,
    task: Task,
    due_string: String,
    duration: Option<u32>,
    spinner: bool,
) -> Result<String, Error> {
    let due_string = if task.is_recurring() {
        format!("{} starting {due_string}", task.due.unwrap().string)
    } else {
        due_string
    };
    let body = if let Some(duration) = duration {
        json!({ "due_string": due_string, "duration": duration, "duration_unit": "minute" })
    } else {
        json!({ "due_string": due_string })
    };
    let url = format!("{}{}", TASKS_URL, task.id);

    request::post_todoist_rest(config, url, body, spinner).await?;
    // Does not pass back a task
    Ok(String::from("✓"))
}
```

Alternatively, you could use `complete` to delay the task to the next occurrence; I know that would add an undeserved increment to the completed count. Feel free to reopen to continue the discussion :+1:
